#!/bin/sh

set -e

. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        # Activate package triggers.
        dpkg-trigger update-workbench

        # Create the default configuration.
        echo "Updating configuration database ..."
        omv-confdbadm create "conf.service.mergerfs"
        if [ -n "$2" ]; then
            omv-confdbadm migrate "conf.service.mergerfs" "$2"
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

exit 0
